### ISSUE TITLE
Invalid return statement

### ISSUE THREAD

**Issue by Vivek-anand-jain** [rathoresrikant/Implementation-of-Curvy-RED-in-ns-3#1]
https://github.com/rathoresrikant/Implementation-of-Curvy-RED-in-ns-3/blob/cea580a8ca2fa83b089117d2d06f223031e36afb/src/traffic-control/model/dual-q-coupled-curvy-red-queue-disc.cc#L359

**Comment by vipin-singh1** [comment]
Removed.
