### ISSUE TITLE
Packet tag should be removed while dequeueing the packet.

### ISSUE THREAD

**Issue by Vivek-anand-jain** [rathoresrikant/Implementation-of-Curvy-RED-in-ns-3#3]
https://github.com/rathoresrikant/Implementation-of-Curvy-RED-in-ns-3/blob/cea580a8ca2fa83b089117d2d06f223031e36afb/src/traffic-control/model/dual-q-coupled-curvy-red-queue-disc.cc#L342

**Comment by rathoresrikant** [comment]
Added logic to remove tag from items before dequeue in both the queues.

**Comment by Vivek-anand-jain** [comment]
Close the issue if addressed.
