### ISSUE TITLE
This won't double value

### ISSUE THREAD

**Issue by Vivek-anand-jain** [rathoresrikant/Implementation-of-Curvy-RED-in-ns-3#4]
m_avgQueuingTime.GetSeconds () / pow (2, m_classicQScalingFact);

https://github.com/rathoresrikant/Implementation-of-Curvy-RED-in-ns-3/blob/cea580a8ca2fa83b089117d2d06f223031e36afb/src/traffic-control/model/dual-q-coupled-curvy-red-queue-disc.cc#L353

**Comment by rathoresrikant** [comment]
I tried using Time in place of double but it displayed and error message showing "cannot convert time to double". So, I think double here is apt. I have also type-casted the RHS.
