### ISSUE TITLE
User doesn't supply this variable.

### ISSUE THREAD

**Issue by Vivek-anand-jain** [rathoresrikant/Implementation-of-Curvy-RED-in-ns-3#5]
https://github.com/rathoresrikant/Implementation-of-Curvy-RED-in-ns-3/blob/cea580a8ca2fa83b089117d2d06f223031e36afb/src/traffic-control/model/dual-q-coupled-curvy-red-queue-disc.h#L183

**Comment by vipin-singh1** [comment]
Moved into variable maintained by Curvy Red.
