### ISSUE TITLE
Modify description of all attributes

### ISSUE THREAD

**Issue by Vivek-anand-jain** [rathoresrikant/Implementation-of-Curvy-RED-in-ns-3#6]
https://github.com/rathoresrikant/Implementation-of-Curvy-RED-in-ns-3/blob/cea580a8ca2fa83b089117d2d06f223031e36afb/src/traffic-control/model/dual-q-coupled-curvy-red-queue-disc.cc#L353

**Comment by rathoresrikant** [comment]
Attribute description modified.
